### ISSUE TITLE
[html5] What "type" of html5 Haxeling uses?

### ISSUE THREAD

**Issue by T1mL3arn** [Haxeling/haxe-starling#4]
I noticed in "project.xml" it uses "dom". Canvas and webgl not works for me. Can you make an explanation in the README(or just here) about available html5 targets?

**Comment by peteshand** [comment]
What IDE are you using?
If you're with FlashDevelop/HaxeDevelop simply open the example app and then select html5 in the target drop down and publish. It's as simple as that.

**Comment by T1mL3arn** [comment]
OpenFl supports  3 type of html5 targets: DOM, Canvas, WebGL. As I understood, for now Haxiling supports only DOM target. Is that right?

**Comment by peteshand** [comment]
Oh right, I see what you're asking now.

It's currently a little confusing in that Haxeling renders only with WebGL, however for it to work OpenFL needs to be set to DOM. This has to do with some #if dom statements within OpenFL.. it something I'd like to look at resolving at some point, because it would be nice to be able to use Starling and hardware accelerated OpenFL in the same app, but I've just not had time, plus it's sometimes hard to get changed merged into OpenFL
