### ISSUE TITLE
Mouse events are not working for html5 target

### ISSUE THREAD

**Issue by NenadBojkovski** [Haxeling/haxe-starling#9]
Hi,

If you wonder why the mouse events are not working on html5 target, here is why.
There is a `touchEventTypes` getter in Starling.hx which is suppose to add mouse events for flash and html5 targets and touch events for mobile targets. The problem is that there is a check there:

``` haxe
        var supportsCursor:Bool = false;
        #if flash
            supportsCursor = Mouse.supportsCursor;
        #end
        if (multitouchEnabled == false || supportsCursor) { 
            types.push(MouseEvent.MOUSE_DOWN);
            types.push(MouseEvent.MOUSE_MOVE);
            types.push(MouseEvent.MOUSE_UP);
        }
```

From this code could be seen that mouse events would work for flash target(if mouse cursor is supported). But for html5 it relies on `multitouchEnabled` which needs to be false. That's actually the problem.
multitouchEnabled getter returns `Multitouch.inputMode == MultitouchInputMode.TOUCH_POINT` while setter sets `Multitouch.inputMode`. However openFL's Multitouch class is not fully implemented. If you take a look at  Multitouch's inputMode getter and setter, the getter always returns `MultitouchInputMode.TOUCH_POINT` and the setter doesn't set anything. Check the code:

``` haxe

    private static function get_inputMode ():MultitouchInputMode {

        return MultitouchInputMode.TOUCH_POINT;

    }


    private static function set_inputMode (inMode:MultitouchInputMode):MultitouchInputMode {

        if (inMode == MultitouchInputMode.GESTURE) {

            return inputMode;

        }

        // @todo set input mode
        return inMode;

    }
```

This way, `multitouchEnabled` would always be true, no matter how one sets it. So, mouse events won't be added hence no mouse interaction possible.

FYI: The bunnymark example on Haxeling's web site (http://blog.peteshand.net/starling-for-haxe/) doesn't have `if (multitouchEnabled == false ...` check and so the mouse events are working.

It would be much appreciated if this issue is fixed by Haxeling or even better by OpenFl. I guess they(OpenFl guys) are not aware of it, but since Haxeling depends on it, it is better if you(Pete) poke them.

**Comment by peteshand** [comment]
Hey there

Thanks for spotting this.. this is due to a recent change made to stop touches and mouse event happening on desktop touch screens... didn't realize it was causing issues in html5. I've changed the default supportsCursor value to true.. while this isn't a perfect fix, it should be good enough to resolve your issue... but yes you're right, a better solution would be to have supportsCursor implemented in openfl.

**Comment by peteshand** [comment]
new version has been pushed to haxelib (0.5.7)

**Comment by NenadBojkovski** [comment]
You are very welcome Pete.
We are investigating haxe/openfl/haxeling to port our monster flash project
to haxe. We are developing prototype which should answer some questions
regarding haxe and html5 target, but in your opinion is haxeling on  html5
target performing well? I mean is it close to as3 starling performance?

Thank you so much!
Best,
Nenad

**Comment by peteshand** [comment]
We've been using Haxeling in a huge project for the past 6 months and it's been going really well. This project is targeting both Adobe AIR and html5, we basically have touch screen interactives and digital signage and then have a "what you see is what you get" html5 CMS editor. Due to this project Haxeling has become very stable. The only performance tip I'd give is to keep away from mixing Haxeling and OpenFL, but other than that the performance is really good.
